### ISSUE TITLE
Alphabetical error in 1.0.0 release

### ISSUE THREAD

**Issue by dixonary** [fbricker/openfl-locale#2]
Hello,

On the version downloaded from haxelib, the "include.xml" file contained a line refering to "java/localeEx/include.xml". However it was supposed to be referring to LocaleEx with a capital L.

Fixing the capital in the <include /> fixed the issue locally.

**Comment by fbricker** [comment]
Done, there's version 1.0.1 published on haxelib :)

Thanks for reporting!
